# Generated by Django 5.1.4 on 2024-12-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyFieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('acres', models.FloatField(blank=True, null=True)),
                ('seed_cost', models.FloatField(blank=True, null=True)),
                ('fertilizer_cost', models.FloatField(blank=True, null=True)),
                ('chemical_cost', models.FloatField(blank=True, null=True)),
                ('crop_insurance', models.FloatField(blank=True, null=True)),
                ('yield_amount', models.FloatField(blank=True, null=True)),
                ('crop', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_data', to='fields.field')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('field', 'year')},
            },
        ),
    ]
