# Generated by Django 5.1.4 on 2024-12-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('fuel', 'Fuel'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
